# Generated by Django 5.2.6 on 2025-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
